### ISSUE TITLE
This version is fork of servicestack.ormlite or new one

### ISSUE THREAD

**Issue by Longnt1208** [Master-Inspire/TheOne.OrmLite#1]
Hi,
I found your lib when trying find orm lib for Oracle with dotnet core. I really like your lib and want to use it into my new project but I saw link in readme to ServiceStack.OrmLite so I wonder that this is new one or fork version of ServiceStack.OrmLite because free version of ServceStack.OrmLite only allow 10 tables. Thanks.

**Comment by Master-Inspire** [comment]
@Longnt1208 forked from ServiceStack.OrmLite, but heavily modified, especially for Oracle .

**Comment by Longnt1208** [comment]
it's really nice work, thank you.
